[model]
name = "kokoro"
repo_id = 'hexgrad/Kokoro-82M-v1.1-zh'

[voices]
default = "zf_001"
available = ["zf_001", "zm_010"]

[performance]
use_gpu = true
batch_size = 8
max_concurrent = 4

[paths]
model_path = "models/kokoro/weights.bin"
vocoder_path = "models/kokoro/vocoder.bin"