[model]
name = "f5-tts"

[voice]
default_voice = "男性声音1"

[performance]
use_gpu = true

[paths]
model_path = "model_download/model_1250000.safetensors"
vocos_path = "model_download/vocos"

voice_path = "voices"